### ISSUE TITLE
Add Estimated start time to amms from templates

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/turbo#105]
Markets created with templates that have an estimated start time need to show in amm

**Comment by justinbarry** [comment]
@Chwy5 Do you mean in the UI?

**Comment by Chwy5** [comment]
yes

**Comment by Chwy5** [comment]
We added to design

**Comment by bthaile** [comment]
Is this good?

![image](https://user-images.githubusercontent.com/3970376/116462795-7d0f0e00-a82f-11eb-8390-66e117cbbcec.png)

**Comment by Chwy5** [comment]
yes for now...we will need to add am/pm to 24 hr conversion

**Comment by Chwy5** [comment]
added - closing
