### ISSUE TITLE
Add resolved tag to markets in portfolio/ My Bets

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/turbo#1077]
Turbo

Add 12px above market title

https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Augur-Simplified-UI?node-id=319%3A4430

![image](https://user-images.githubusercontent.com/39496225/129062860-e3517217-75d8-4274-90d9-466d135a2c97.png)

---

SB

Add 8px above market title

https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Sportsbook?node-id=11063%3A3130

![image](https://user-images.githubusercontent.com/39496225/129067413-911540a0-d1fe-4bb5-8d7d-5b2d2b2c2ffe.png)

**Comment by matt-bullock** [comment]
@JohnDanz tags aren't showing up

**Comment by JohnDanz** [comment]
no resolved markets so
