### ISSUE TITLE
user not getting wmatic when adding additional liquidity

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#1175]
<https://mumbai.polygonscan.com/tx/0xa3809197dfa22f2f0245c5506a8ac59d611286f53247de491bf586e4e45172a1> 

User had 0.07... wmatic pending when they added additional liquidity, transaction indicates the user got zero when they expected to get their pending wmatic.

**Comment by justinbarry** [comment]
Original issue was the reward didn't have any reward tokens. Hijacking this to include the bad math that was happening when rewards were being paid out over multiple days.

**Comment by robert-e-davidson3** [comment]
Can this be closed @justinbarry ?
