### ISSUE TITLE
Mint complete sets

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/turbo#1183]
https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Augur-Simplified-UI?node-id=3613%3A196888

Remove fee and replace with Mint Complete Sets button to top of modal

If user clicks mint complete sets button at top of the modal they will be taken into the mint complete sets flow. Clicking the back arrow will take them back to the Add liquidity screen.

![image](https://user-images.githubusercontent.com/39496225/132241198-b9c9d29d-c9c5-468a-8bfd-015010f5f407.png)

**Comment by Chwy5** [comment]
Has been added - closing
