### ISSUE TITLE
UI changes for Reward updates

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#1215]
UI updates
 - [x] 1. no approval needed to remove liquidity if rewards are enabled for the market factory
 - [x] 2. add and remove liquidity through the master chef, address will be in marketFactories in addresses.ts
 - [x] 3. calls to get pending rewards come from master chef contract instead of ammFactory
 - [x] 4. note: ammFactory is now the first parameter 
 - [x] 5. V3, bonus cutoff timestamp property (to be added to fetchers)
~~6. V2, bonus cutoff add multicall per market~~
 - [x] 7. Add rewards to APY calculation
 - [x] 8. Add new methods for calling master chef contract to "add initial liquidity", "add additional liquidity" and "remove liquidity", only for marketFactories that have rewards enabled.
 - [x] 9. Add message to use they will lose their bonus if add/remove liquidity
  - [x] 10. make sure to get trading fee from fetcher

**Comment by Chwy5** [comment]
closing
