### ISSUE TITLE
Graph: index V3 markets  (missing Nfl Market on Graph)

### ISSUE THREAD

**Issue by iRhonin** [AugurProject/turbo#1249]
Hi, 

I am integrating Augur inside Mask.
It is like a component in Twitter with market data and actions like Buy/Sell/Add/Remove liquidity...

Until now, I was using a combination of Graph and contracts to fetch market data,

But seems the Nfl market query does not return any result.

Also, the Market schema missing the Nfl market.

Using this Graph: https://thegraph.com/legacy-explorer/subgraph/augurproject/augur-turbo-matic

![image](https://user-images.githubusercontent.com/13151232/133760540-04010836-d83d-4085-99c4-4ba97d3babbf.png)
![nfl-market-missing-augur](https://user-images.githubusercontent.com/13151232/133761000-19c9abb9-7816-4e95-88f9-16ae8da5f3ae.png)

**Comment by namankumar** [comment]
Use the fetcher contracts to pull in V3 market factories. This will make V3 markets available to 3rd parties.

**Comment by iRhonin** [comment]
> Use the fetcher contracts to pull in V3 market factories. This will make V3 markets available to 3rd parties.

Oh, thanks! where can I find them?

**Comment by namankumar** [comment]
@iRhonin devs working on augur will pull in the market factories in the next week. If you could wait for their PR to be merged, this should *just* work for you without additional work from you.

**Comment by bconfortin** [comment]
Hi @iRhonin 
I've added NFL and MMA markets that were missing in the latest deploy.
I also added nflMarkets to the market schema.

![Captura de Tela 2021-09-21 às 01 11 05](https://user-images.githubusercontent.com/10351013/134110440-c7d269e8-be55-4831-a316-85487be21242.png)

**Comment by iRhonin** [comment]
> Hi @iRhonin 
> I've added NFL and MMA markets that were missing in the latest deploy.
> I also added nflMarkets to the market schema.
> 
> ![Captura de Tela 2021-09-21 às 01 11 05](https://user-images.githubusercontent.com/10351013/134110440-c7d269e8-be55-4831-a316-85487be21242.png)
> 
> 
> 

Hi @bconfortin, thank you!

**Comment by iRhonin** [comment]
It seems `nflMaket` is not resovling any market:
![image](https://user-images.githubusercontent.com/13151232/134265107-7aef2edb-d3c6-4702-bd32-33c51a5a881d.png)

@bconfortin
