### ISSUE TITLE
couldn't sell shares to AMM with plenty of liquidity

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#1294]
ammFactory: 0xdcf4173fc3947bc2cbab929559b7f38cb25bef34
marketFactory: 0x31ebd440f52b537845126e9d013febd9e610f78a
marketId: 61
user account: 0x0c9e1ec8Db2132eF656b250b6AeceaD3D0313b08

Users share balances
['10000000002120540747800', '23024694116861196951351', '7000000001800863115478']

user trying to sell `7000000000000000000000` shares of `outcome 1`, 

balancer pool 
id: `"0x360E5D0DcFEDccdf4AcAF53e58aC2C431b4CBb29"`
balances `['14191664271879459252200', '1166970157138803048649', '17191664272199136884522']`

Here is the transaction:
https://mumbai.polygonscan.com/tx/0x007e1eb5c35eb49324c6b8a675c6741e66a8a0125fd7b03cd3fdb82ef0392c4d

share tokens in which is a result of `calcSellCompleteSets` call
`['43734372222870080077', '4368547337688141851683', '2587718290084837991646']`

Here is the failure when trying to manually sell shares.
![image](https://user-images.githubusercontent.com/3970376/134549572-85403ece-4f08-414d-9213-7ee9143fc403.png)

**Comment by justinbarry** [comment]
Won't fix.
