### ISSUE TITLE
Invalid price for No Contest

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#1298]
prob need to round up for No Contest price
![image](https://user-images.githubusercontent.com/3970376/134561422-ff2c7573-b335-44f5-accf-220330423cf6.png)

**Comment by Chwy5** [comment]
Still seeing this...happened of missles vs torpedos market

![image](https://user-images.githubusercontent.com/41301809/134719333-dd958038-42ea-48ca-92fa-3c979dbf279d.png)

**Comment by Chwy5** [comment]
fixed - closing
