### ISSUE TITLE
Null Fields on NFL Graph

### ISSUE THREAD

**Issue by iRhonin** [AugurProject/turbo#1313]
NFL market now exists but fields are null.

![image](https://user-images.githubusercontent.com/13151232/134770859-006dd196-a325-4fe2-b45a-cd59aaa00d1d.png)

**Comment by namankumar** [comment]
@bconfortin could you investigate pls, lmk how big of an issue this is

cc: @bthaile @pgebheim

**Comment by iRhonin** [comment]
@namankumar is this fixed?

**Comment by namankumar** [comment]
@iRhonin yes, try and let us know if there's a problem

**Comment by iRhonin** [comment]
Thank you for the fix!

All fields now resolving except `endTime`.

> @iRhonin yes, try and let us know if there's a problem

**Comment by namankumar** [comment]
@iRhonin looking into it, will post update here
