### ISSUE TITLE
Over/Under has incorrect label for `Tie/No Contest`

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#1330]
2 issues:
1. In this example below `47.5` should be removed. 
2. `Tie/No Contest` should be last outcome

![Screen Shot 2021-09-29 at 5 34 11 PM](https://user-images.githubusercontent.com/3970376/135357889-e4d264b3-ac79-4694-9b64-ebfc9a53beea.png)

**Comment by Chwy5** [comment]
fixed- closing
