### ISSUE TITLE
Add liquidity showing up twice per `addLiquidity` tx

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#1336]
![image](https://user-images.githubusercontent.com/3970376/135492032-ef359030-4894-4edc-a317-dbd0e3e1ed96.png)

graph returning both addLiquidity transactions from ammFactory and masterChef. 

in the UI filter ammFactory add/remove liquidity if market factory has rewards true.

**Comment by Chwy5** [comment]
fixed - closing
