### ISSUE TITLE
Sport Fetcher inconsistently returning old Markets

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#1340]
MLB factory config passed into fetcher and returns correct number of markets
![image](https://user-images.githubusercontent.com/3970376/135541248-605745f2-353f-428a-a819-b13b8cf50738.png)

on a different call returns old markets with new markets
![image](https://user-images.githubusercontent.com/3970376/135541290-7a1e6543-9307-497a-a586-31f43361d2c6.png)

The old markets don't look resolved:
market: 0x03810440953e2bcd2f17a63706a4c8325e0abf94-1
![Screen Shot 2021-09-30 at 6 01 07 PM](https://user-images.githubusercontent.com/3970376/135541430-3feaa679-74cc-48f3-925b-d1a233eeeb7f.png)

**Comment by robert-e-davidson3** [comment]
Should be fixed with #1343
