### ISSUE TITLE
mobile: bring up number pad rather than keyboard when user enters wager in betslip

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/turbo#1380]

**Comment by matt-bullock** [comment]
@JohnDanz I'm still seeing the keyboard, not number pad

**Comment by bconfortin** [comment]
That's a Metamask browser limitation, I don't think we can do anything about it.
It doesn't have any kind of documentation and it doesn't even show up on https://caniuse.com/, where you can see which features are supported by different browsers.

It's working as intended on Chrome for both iOS/Android (using WalletConnect + MM).

**Comment by bconfortin** [comment]
Opened an issue at the MetaMask Mobile repository:
https://github.com/MetaMask/metamask-mobile/issues/3296
