### ISSUE TITLE
Sorcerers vs Barbarians "No Contest" bet shows NaN

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#1403]
![image](https://user-images.githubusercontent.com/3970376/136049139-5149f479-f762-47e6-9f21-40cc72cc2dc4.png)

bet $200 on "No Contest" the `to Win` shows NaN.

guess is that the `toWin` is using formatted value and can't do math with commas.

**Comment by Chwy5** [comment]
not seeing this since real data - closing
