### ISSUE TITLE
Filter MMA events for the main card only

### ISSUE THREAD

**Issue by namankumar** [AugurProject/turbo#1416]
Returned MMA data has all fights for a given night whereas we only need the main card. This ticket is to filter for the main card. 

@pgebheim has determined this is possible and can be implemented by checking a variable.

**Comment by namankumar** [comment]
Being fixed in #1435

**Comment by namankumar** [comment]
Not fixed in 1425, so reopened

**Comment by robert-e-davidson3** [comment]
Added to PR https://github.com/AugurProject/external-adapters-js/pull/18
