### ISSUE TITLE
JS package that generates human readable market info data for UI

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#142]
Purpose
====

Rundown sourced markers will not have any human readable information on them. Just machine readable data (event_id, team_id, etc.). Human readable information is needed for the UI.

Process
====

- [x] Pull team names and associated IDs from the rundown.
- [x] Identify market strings and outcomes needed for the various market types and or sports.

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/turbo/pull/155 - adds a task to smart to fetch and create a teams object which we will want to store as json and pull into the UI. This currently simply logs out the results and doesn't do anything with them.
