### ISSUE TITLE
Setup polygon testing environment

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#1425]
- [x] Add a duplicate network to hardhat config for network id 137 and deploy
- [x] Transfer ownership of master chef to 0x486a583DB850d87A18e15B9350021921331A3828
- [ ] Update Augur CL node to point at new contracts deployed above
- [x] Update addresses.ts to be keyed by network name vs network id
- [ ] Update UIs to use network name vs network id when pulling addresses for an environment

**Comment by namankumar** [comment]
Pushed to backlog as Polygon is up and running again.
