### ISSUE TITLE
MMA market did not resolve

### ISSUE THREAD

**Issue by namankumar** [AugurProject/turbo#1434]
This MMA market had fighters change (per ESPN) and it correctly shifted the odds to 1.000 for No Contest. However, the market did not resolve. 

Market ID: 0x6d2e53d53aec521dec3d53c533e6c6e60444c655-23

![image](https://user-images.githubusercontent.com/330364/136440214-e816e404-329f-4e93-8d8e-db0a75ea272f.png)

**Comment by robert-e-davidson3** [comment]
Fixed. Turns out this wasn't exactly a bug.

We had code in place to resolve this as No Contest but that code would not have run until the event resolved. The fix was to resolve events with changed fighters immediately.
