### ISSUE TITLE
MLB markets not being created

### ISSUE THREAD

**Issue by namankumar** [AugurProject/turbo#1462]
There are three games today but no markets on Turbo.

![image](https://user-images.githubusercontent.com/330364/136994662-bbfecb7d-28df-4e95-8a91-2add16ef54eb.png)

**Comment by namankumar** [comment]
Likely a timezone issue - adapter uses UTC for baseball tz.

**Comment by robert-e-davidson3** [comment]
Two adapter fixes:
- [x] TheRundown expects eastern time not utc
- [x] Our rundown code skips the current day but shouldn't

**Comment by robert-e-davidson3** [comment]
https://github.com/AugurProject/external-adapters-js/pull/18
