### ISSUE TITLE
Display messages in UI related to reward depletion

### ISSUE THREAD

**Issue by namankumar** [AugurProject/turbo#1473]
Display these messages on the add/remove liquidity page:

1. Display this message when the amount of wmatic left in MasterChef is less than 3000 wmatic.
Message: "Rewards contract low balance. Learn More."

where Learn More links to the LP Help Page, that says: 

"Third parties may provide LP rewards using Augur smart contracts.  Users must remove their liquidity to claim their rewards before funds are depleted.  LP's may remove their liquidity after the rewards contract is depleted, to return their remaining LP available balance, but estimated rewards earned will not be included."

2. Display this message when the amount of wmatic left in MasterChef is 0.
Message: " Rewards depleted."

**Comment by bthaile** [comment]
Code was added to handle these two conditions, closing
