### ISSUE TITLE
Market Factory contract impl

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#148]
MarketFactory that takes the following set of data. This should cover the case of baseball/basketball.

For creation:

```
createMarket(
eventid, 
home_team_id, 
away_team_id, 
home_spread, 
over_under_total, 
estimated_start_time_in_unix_timestamp_format)
```

NOTE: Spread can be negative and it indicates the home team is the favorite.

For resolution

`resolveMarkets(eventid, homescore, awayscore)`

**Comment by justinbarry** [comment]
Related: #35

**Comment by robert-e-davidson3** [comment]
Added to the refactor PR
