### ISSUE TITLE
Sportsbook: Add USDC icon to user balance in top bar

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/turbo#1488]
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Sportsbook?node-id=11045%3A9350

![image](https://user-images.githubusercontent.com/39496225/137777599-f48791d4-49f7-4919-9f6e-2482a25f0559.png)

**Comment by mjgiannelli** [comment]
completed on forked repo on local system. working on #1489 now. will include both requests on one PR

**Comment by JohnDanz** [comment]
Thanks @mjgiannelli
