### ISSUE TITLE
Sportsbook: Add USDC icons to bottom part of betslip

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/turbo#1489]
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Sportsbook?node-id=11045%3A9521

![image](https://user-images.githubusercontent.com/39496225/137779089-95c57d42-1937-4071-8cb1-97597fc5e41f.png)

**Comment by JohnDanz** [comment]
@mjgiannelli thank you for this, but turns out we actually don't want icons down there. Can you remove them please in another PR?

**Comment by mjgiannelli** [comment]
> @mjgiannelli thank you for this, but turns out we actually don't want icons down there. Can you remove them please in another PR?

@JohnDanz removed in pr #1509
