### ISSUE TITLE
Add available USDC user balance to top bar on mobile

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/turbo#1504]
![image](https://user-images.githubusercontent.com/39496225/138145707-b1caac4a-0187-416e-abf3-64e5a7897b1c.png)

https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Sportsbook?node-id=11436%3A300107

**Comment by matt-bullock** [comment]
Can you right align this. Like so:

![image](https://user-images.githubusercontent.com/39496225/138320852-be7aed60-ee95-4bf4-97c9-6d26ef1df6bf.png)

**Comment by mjgiannelli** [comment]
> Can you right align this. Like so:
> 
> ![image](https://user-images.githubusercontent.com/39496225/138320852-be7aed60-ee95-4bf4-97c9-6d26ef1df6bf.png)

Adjusted. PR #1512

**Comment by matt-bullock** [comment]
Thanks! Looks good
