### ISSUE TITLE
Cash Out Shares button appears when you cannot cash out

### ISSUE THREAD

**Issue by akreider** [AugurProject/turbo#1507]
I'm seeing the "Cash Out Shares" button appear on the Portfolio page when I have only two of the three contracts for a market.  So it gives me a popup error if I click on it "Failed"

![image](https://user-images.githubusercontent.com/2105954/138151799-0eb88738-9c25-4fe6-8c93-5647b6bf7aa2.png)

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/turbo/pull/1513 fixed with this PR -- should be fixed in the next published release.
