### ISSUE TITLE
Claiming Winnings Amount is Wrong

### ISSUE THREAD

**Issue by akreider** [AugurProject/turbo#1514]
I had a button to Claim Winnings for an amount (say x).  The actual amount that was claimed as twice as large.  So my portfolio value fell by that 2x amount, and my USDC balance increased by that 2x amount.  It's possible this is a loading / network issue, but other things were loading pretty fast.

**Comment by akreider** [comment]
I think the problem is that Claiming Winnings only counts the amount of money you won compared to your portfolio value.   I wonder if this process could be clearer?  For instance, you are actually claiming winnings AND cashing in on your portfolio value.

Also I think the entire process should be rethought to include Claiming Losses as users should be equally aware of them. In general, there should be a single place where you can easily see all your wins and losses (and eventually a CSV export of them).

In counting wins and losses, I think it makes more sense to value the position at the cost of acquisition than the last known market price.

**Comment by bthaile** [comment]
Two concept at play with claiming winnings. 
`Profit/Loss` is the amount of won
`Proceeds` is the total amount claimed (wager and profit/loss)

The design decision was made with the thought that ppl only care profit and loss, so "claim winnings" is profit/loss centric, but when users actually claims they get total proceeds back. It does get confusing when trying to track profit and loss. 

On portfolio the "activity" shows the proceeds claimed. 
closing

**Comment by akreider** [comment]
At least one other user expressed the same confusion, and I suspect others share it.

Claim Winnings does a poor job of tracking losses.  It is more accurate to say it is profit-centric.

The windows on the side of the portfolio page don't seem to include losses.  For instance, they could show "Claimed proceeds 0.00 (a loss) for Market X". It'd be more useful if they showed the number of shares, and the initial cost (ideally on new page - like Account History).  Referring people to the transaction on Polygon Explorer is not a good solution.
