### ISSUE TITLE
Weird valuation of liquidity

### ISSUE THREAD

**Issue by akreider** [AugurProject/turbo#1522]
In this market someone added $500, then removed "$0.00" (all of their liquidity).  They did this when the No Contest was at 1.00 - so they probably realized they made a mistake adding it in the first case.

I'm guessing they actually added "$0.00" (and got $500 worth of tokens in the two teams) and then removed it.

https://bafybeickragxfpsva6b5zbpcmfiu35aeuawuzmsscvmiyhpe44mbyxn6ty.ipfs.dweb.link/#!/market?id=0x1f3ef7ca2b2ca07a397e7bc1beb8c3cffc57e95a-178

![image](https://user-images.githubusercontent.com/2105954/139182701-042ca7ea-9b1f-4790-8cfc-df85a12cf1dc.png)

**Comment by bthaile** [comment]
<https://polygonscan.com/tx/0x9db378f792d5c72ba433a6205956268c5cda7f58f8ccce9a7dbc2175e125a6b7> 

Here is the transaction associated with the `Liquidity Removed` transaction in the table. It was a remove liquidity, I suspect that they left their liquidity in too long and all winning outcome shares were bought leaving them with worthless shares, `Total Value` would be $0.00.
closing

**Comment by akreider** [comment]
I think the liquidity was worth $0 when it was added (14 minutes ago) and $0 when it was withdrawn (6 minutes ago). There were NO trades done between these two events and therefore the prices shouldn't have changed.

I'm referring to the two liquidity moves by 0xefbc

It was worth $0 when added because No Contest was at 1.00 - so almost all the liquidity went into buying shares for the two teams (and their portfolio value)

This is a bug and should be reopened.
