### ISSUE TITLE
Inaccurate My Rewards on Pools page

### ISSUE THREAD

**Issue by akreider** [AugurProject/turbo#1523]
This screenshot claims I'm getting 0.27 wMatic My Rewards on $2 LP that has been in the market for 45 minutes. It is incorrect.

If My Rewards is assuming that your fraction of the liquidity pool will be constant, this is a bad assumption.  This is especially bad for the first people to add liquidity as it appears that you have made the money.   If it's an estimate, it should be displayed as such.

It also increases over time and this makes me think that I've already been given these rewards and just need to hold to closing time to collect them.  For instance, I'm now up to 0.32 wMatic.

![image](https://user-images.githubusercontent.com/2105954/139187106-007a0600-375a-4afc-96cd-0fe0775a066c.png)

**Comment by bthaile** [comment]
"My Rewards" is the rewards earned for being in the liquidity pool. $1.38 of liquidity is 4.7% of the total $28.60 liquidity. So you would get 4.7% of the block rewards. 
You can verify by removing liquidity and seeing how much wmatic you receive in the transaction explorer https://polygonscan.com

closing

**Comment by akreider** [comment]
I left the liquidity in for another 16 hours and got 0.32 Matic when I cashed out.  Though what happened is that someone added $8k of liquidity (making my $2 tiny). I thought I've seen my matic rewards be realized as less than the number given before, but it looks like it didn't happen this time.
