### ISSUE TITLE
Deploy task can use external addresses

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#158]
Some of the contracts like the Cash ones really ought to be deployed rarely since they're just stand-ins. We don't change their code and it's annoying to redo approvals and faucets and such.

**Comment by robert-e-davidson3** [comment]
This is necessary for the chainlink test code since it has to point to a link token and an oracle that don't exist on localhost.

**Comment by phoebemirman** [comment]
associated with #214

**Comment by robert-e-davidson3** [comment]
we're doing this with hardhat-deploy and manually adding fields to deploy config
