### ISSUE TITLE
User should be able to sell token for collateral in balancer pool

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#18]
Users must be able to sell one of their tokens to the balancer pool and receive collateral back. This calculation is too complex to be done in the EVM so a typescript function is needed. This applies to the AMMFactory sell and exitPool soldiity methods.

(AMMFactory here is unrelated to the old AMMFactory. They just do the same sort of thing but very differently.)

This ticket also includes tests for adding, removing, then adding liquidity. As well as buy-sell-buy.

**Comment by pgebheim** [comment]
I think we should start with ONLY handling a 3-pool!
