### ISSUE TITLE
Create basic markets

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#22]
use script to create markets for testing on kovan
use hardhat to create markets passing in market description.

use test to figure out how to create markets
https://github.com/AugurProject/turbo/blob/master/packages/smart/test/turbo-test.ts

add convenience method to create market even if hatchery doesn't exist. 
add getOrCreateHatchery(...)

**Comment by robert-e-davidson3** [comment]
We have canned market task now. It doesn't create a market factory as-need but we do so during deploy anyway.
