### ISSUE TITLE
Create MMA Market Factory

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#232]
A little more detail.

Market factory that creates 2 markets for an event:
head to head
over/under.

Will follow the same pattern as the sports market factory. Need to investigate:
1. Are fighter names organized like team names
2. Are there "lines" for over/under

resolution, need 3 values:
1. round number the fighted ended.
2. need each fighters round scores added up to produce total points per fighter, which will produce 2 numbers.

**Comment by robert-e-davidson3** [comment]
We dropped over-under so this ended up much simpler.
