### ISSUE TITLE
Add claim fees button

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/turbo#236]
Only shows for market creators when they have generated any fees

https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=93%3A17690

![image](https://user-images.githubusercontent.com/39496225/115252714-02a60600-a12c-11eb-979d-8d21cea5b6e3.png)

**Comment by Chwy5** [comment]
not needed - closing
