### ISSUE TITLE
add liquidity modal doesn't give indication user is changing price

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#247]
input doesn't look like user can add prices.

![2021-04-20 12 19 14](https://user-images.githubusercontent.com/3970376/115438193-b792fe00-a1d2-11eb-930d-b81ed90519a6.gif)

**Comment by matt-bullock** [comment]
Can you remove the hand pointer tool when hovering the outcomes as you can't click these. Text tool should appear when hovering the outcome price inputs
