### ISSUE TITLE
Spread market outcomes names are confusing

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#254]
outcomes should be standard, UI and contracts need to agree on the outcomes so that the market will resolve correctly. Underdog and Favorite are determined by bookie line. I don't think the contracts should add logic to determine that, It should just put home team as outcome 1 and away team as outcome 2. That is what the UI is doing, easily changed so that both UI and contracts are on the same page. 

![Screen Shot 2021-04-20 at 16 43 23](https://user-images.githubusercontent.com/3970376/115467732-9690d400-a1f7-11eb-9328-73a0d1910f5e.png)

Also we need standard ERC20 names so that when users look at block explorer their trade makes sense. "Home" and "Away" makes sense for head-to-head and spread markets, over/under outcomes need to switch imo. 

propose 2 changes:
1. change head-to-head outcomes to "No Contest", "Away", "Home"
2. change spread outcomes to "No Contest", "Away", "Home"
3 change over/under outcomes to "No Contest", "Over", "Under"

**Comment by robert-e-davidson3** [comment]
The spread resolution logic is wrong as it stands so this change is necessary for Phase 1.

**Comment by robert-e-davidson3** [comment]
Fixing resolution logic is part of #322 now.
