### ISSUE TITLE
Consolidate constants and utils

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#26]
The repo is growing fast so we are generating some tech debt.

This ticket is for consolidating constants and utility functions/classses into a single file/set of files.

Constants like INVALID and YES/NO names and symbols.
Utility functions like mapOverObject.

There probably isn't enough to bother with yet (2020-03-23) but if someone wants a good jump-in point to the turbo repo, this is a good ticket to knock out in a day while introducing you to most of the typescript codebase.

**Comment by bconfortin** [comment]
I am currently cleaning dead code in simplified, I can do that next.
