### ISSUE TITLE
show user's percentage of the pool

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#268]
when user adds additional liquidity show the percentage of the pool they will have after adding. 

This relies on other ticket  <https://github.com/AugurProject/turbo/issues/257> UI needs to know the estimated lp tokens the user will receive. 

![image](https://user-images.githubusercontent.com/3970376/115568702-2c714100-a282-11eb-9ef0-bd44bba05e51.png)

**Comment by Chwy5** [comment]
added -closing
