### ISSUE TITLE
(depends on good sell shares estimate) sell shares tx fails, cuz minAmount is zero

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#272]
Issue is that min amount is zero.  It's zero because slippage from estimate sell is wrong. 

temporary work-around: By setting min amount to 0.01 USDC the transaction is confirmed. 

params used to call `sellForCollateral`:
```
0x397018eFcC4780921D932ef67455E8Af0eCC4efA 
marketId 11 
outcome 0 
amount 1000000000000000000 
min amount 0
```
sell shares estimate is successful but tx fails. MM gas estimate fails as well
<https://kovan.etherscan.io/tx/0x238b0b3229e0ba542b19c58afaa98bbed4abba1579856c80f0dc9778d2747ae4>

![image](https://user-images.githubusercontent.com/3970376/115575275-05b60900-a288-11eb-88c9-fa91e8c9b55f.png)

balancer pool contract isn't verified so tenderly isn't helpful.

**Comment by robert-e-davidson3** [comment]
This is due to the changes @justinbarry made. Now there's no longer a `min amount`. Instead, you specify how many complete sets you will sell. To add potential slippage you would increase the `amount`, so you have more wiggle room.

**Comment by bthaile** [comment]
we'll need to do testing and changes if we need to address failed transactions because min amount complete sets is too optimistic.
