### ISSUE TITLE
UI accessibility pass

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/turbo#302]
Make it easy to tab through page elements with a keyboard.
Give proper labels to navigation items so the screen reader can recognize them.
Click areas are large enough to easily navigate to with a mouse (or finger if it is a touch screen).
Dropdowns open and close using the Enter and ESC keys.
There is a proper contrast between colors.

**Comment by namankumar** [comment]
@justinbarry @phoebemirman pretty important for Augur but would recommend scheduling this after MVP launch as we haven't yet seen evidence that this is a must have requirement for any user for launch @Chwy5
