### ISSUE TITLE
pending tx count is incorrect

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#318]
![image](https://user-images.githubusercontent.com/3970376/116124423-e5bc8600-a689-11eb-8dcc-b5b2fec25901.png)

pending tx count gets off if user refreshes. seems that local storage doesn't get cleared when the tx gets confirmed.

**Comment by JohnDanz** [comment]
unable to reproduce after trying a number of different ways to mess with pending. perhaps this was just bad kovan syncing or something? closing for now... if this is a bug it should re-surface.
