### ISSUE TITLE
Market Resolution Logic

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#322]
How should markets be resolved?

Note that these rules are not yet decided upon. This ticket includes not just implementing this logic but also figuring the logic to use.

**Happy Case: Event took place and produced scores.**
Head-To-Head market. If Home score is equal or greater than Away score than Outcome 1 wins.
If Away score is larger than Outcome 2 wins.

Spread market: If the spread is equal or greater than the target then Outcome 1 wins.
If the spread is below the target then Outcome 2 wins.

Over-Under market: If the total score is equal or greater than the target then Outcome 1 wins.
If the total score is below the target then Outcome 2 wins.

**Sad Case: Canceled**
If an event is cancelled then Outcome 0 (No Contest) wins for all markets.

**Sad Case: Postponed**
If an event is postponed then Outcome 0 (No Contest) wins for all markets.
QUESTION: Do postponed events get a new Event ID if they get a new date?
If they keep the same event ID then leave the markets resolved as No Contest.
If the event gets a new ID then treat it like a new event. We can't tell the difference anyway.

**Sad Case: Date Changed**
QUESTION: Can dates change without becoming postponed?
QUESTION: Do we want to update the market times or resolve the market as No Contest?

**Comment by justinbarry** [comment]
Two things to do:
1. We need to verify the rundown returns data in the format we expect in the case of delayed or cancelled games.
2. Is the source the rundown uses a league source.

**Comment by Chwy5** [comment]
Confirmed with Baseball, it returns what we need...
but there have been no shortened BB games recently to check

**Comment by robert-e-davidson3** [comment]
The rules as written right now:
1. If the event state is NOT final then resolve as No Contest. So canceled and postponed games resolve as No Contest.
2. Ties resolve as No Contest.
3. In Head to Head markets, Home and Away scores are simply compared. If Home has a greater score than the winning outcome is Home. Same for Away.
4. In Spread markets, the spread is calculated as `HomeScore - AwayScore` and compared against the target spread specified at market creation. Otherwise the same as Head to Head: if the spread is greater than the Target than the Home outcome wins.
5. In Over Under markets, the total is calculated as `HomeScore + AwayScore` and compared against the target total specified at market creation. Otherwise the same as the Head to Head and Spread markets.

**Comment by pgebheim** [comment]
This is correct, except that for (1) it should NOT resolve if the event state is SCHEDULED or another in-progress state, to protect against accidental submissions.

**Comment by robert-e-davidson3** [comment]
> This is correct, except that for (1) it should NOT resolve if the event state is SCHEDULED or another in-progress state, to protect against accidental submissions.

Ah ok will add this case to just skip resolution.
