### ISSUE TITLE
show user's current percentage of the pool

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#333]
in remove liquidity modal show user's current percentage of the pool

![image](https://user-images.githubusercontent.com/3970376/116419961-28559e00-a803-11eb-94bc-19f33b85d957.png)

**Comment by JohnDanz** [comment]
<img width="1164" alt="Screen Shot 2021-04-28 at 1 14 48 PM" src="https://user-images.githubusercontent.com/10524630/116452981-f0ab1e00-a823-11eb-9951-3f00ff3a4927.png">
