### ISSUE TITLE
Design for resolution rules for each type of sports market.

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#362]
MLB Moneyline Rules:

The results of a game are official after (and, unless otherwise stated, bets shall be settled subject to the completion of) 5 innings of play, or 4.5 innings should the home team be leading at the commencement of the bottom of the 5th innings. Should a game be called, if the result is official in accordance with this rule, the winner will be determined by the score/stats after the last completed inning.

If the game does not reach the "official” time limit, or ends in a tie, the market should resolve as 'No Contest'.

If the game is not played, the market should resolve as 'No Contest'.

Extra innings count towards settlement purposes.

Results are determined by the natural conclusion and do not recognize postponed games, protests, or overturned decisions.

MLB RunSpread Rules:

The results of a game are official after (and, unless otherwise stated, bets shall be settled subject to the completion of) 5 innings of play, or 4.5 innings should the home team be leading at the commencement of the bottom of the 5th innings. Should a game be called, if the result is official in accordance with this rule, the winner will be determined by the score/stats after the last completed inning.

If the game does not reach the "official” time limit, or ends in a tie, the market should resolve as 'No Contest'.

If the game is not played, the market should resolve as 'No Contest'.

Extra innings count towards settlement purposes.

Results are determined by their natural conclusion and do not recognize postponed games, protests, or overturned decisions.

MLB Over/Under Run-Line Rules:

The results of a game are official after (and, unless otherwise stated, bets shall be settled subject to the completion of) 5 innings of play, or 4.5 innings should the home team be leading at the commencement of the bottom of the 5th innings. Should a game be called, if the result is official in accordance with this rule, the winner will be determined by the score/stats after the last completed inning.

If the game does not reach the "official” time limit, the market should resolve as 'No Contest'.

If the game is not played, the market should resolve as 'No Contest'

Extra innings count towards settlement purposes.

Results are determined by their natural conclusion and do not recognize postponed games, protests, or overturned decisions.

NBA Moneyline Rules:

At least 43 minutes of play must have elapsed for the game to be deemed official. If the game is not played or if less than 43 minutes of play have been completed, the game is not considered an official game and the market should resolve as 'No Contest'.

Overtime count towards settlement purposes..

Results are determined by their natural conclusion and do not recognize postponed games, protests, or overturned decisions.

NBA Point Spread Rules:

At least 43 minutes of play must have elapsed for the game to be deemed official. If the game is not played or if less than 43 minutes of play have been completed, the game is not considered an official game and the market should resolve as 'No Contest'.

Overtime count towards settlement purposes..

Results are determined by their natural conclusion and do not recognize postponed games, protests, or overturned decisions.

NBA Over/Under Rules:

At least 43 minutes of play must have elapsed for the game to be deemed official. If the game is not played or if less than 43 minutes of play have been completed, the game is not considered an official game and the market should resolve as 'No Contest'.

Overtime count towards settlement purposes..

Results are determined by their natural conclusion and do not recognize postponed games, protests, or overturned decisions.

**Comment by Chwy5** [comment]
Closing
