### ISSUE TITLE
after add liquidity prices are incorrect

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#371]
User adds liquidity with prices, after the amm is created the prices are switched.

![Screen Shot 2021-05-03 at 08 39 01](https://user-images.githubusercontent.com/3970376/116883402-2fa5ee80-abeb-11eb-8a2b-57fcaa372df8.png)

![Screen Shot 2021-05-03 at 08 41 22](https://user-images.githubusercontent.com/3970376/116883568-5d8b3300-abeb-11eb-9f69-99c7c72f7b3d.png)

**Comment by Chwy5** [comment]
this is fixed
