### ISSUE TITLE
out of gas failure

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#391]
add liquidity
https://kovan.etherscan.io/tx/0x1630dea31ad947965f8cc4130134c60e91d1b06d8f6bc333897d508bf9426936

buy
https://dashboard.tenderly.co/tx/kovan/0x5ee7f61e96dbe2d7f73343944327a16bc22fc691e26d367808060dacd1179462

Transactions are running out of gas, add liquidity and the buy tx.

Thoughts:
 - Is MM not estimating gas correctly?
 - Does the UI need to manually estimate gas?

@justinbarry 
Are the above legit running out of gas and the estimate was low or is there run away logic?

**Comment by justinbarry** [comment]
Stale.
