### ISSUE TITLE
showing positions when user has zero shares

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#409]
user got shares when adding additional 

![Screen Shot 2021-05-05 at 10 12 06](https://user-images.githubusercontent.com/3970376/117164620-66fed180-ad8a-11eb-9500-2992ad2b2632.png)

![Screen Shot 2021-05-05 at 10 14 44](https://user-images.githubusercontent.com/3970376/117165510-2b183c00-ad8b-11eb-8569-258021eaadf6.png)

Don't show "dust" positions. filter out positions less than 4 decimals of shares

**Comment by Chwy5** [comment]
fixed closing
