### ISSUE TITLE
user LP but percentage is incorrect

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#410]
user added additional liquidity to the pool. the percentage should be the user's percentage of the pool after they added. total supply is on the amm

![Screen Shot 2021-05-05 at 10 13 26](https://user-images.githubusercontent.com/3970376/117165173-dffe2900-ad8a-11eb-913b-76345ccd4e02.png)

**Comment by Chwy5** [comment]
Fixed - closing
