### ISSUE TITLE
User's positions don't show after removing liquidity

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#425]
user added liquidity, there were trades then user removes liquidity. The remove liquidity shows the user will receive market outcome shares. The UI doesn't display the user's positions

![image](https://user-images.githubusercontent.com/3970376/117316344-223c6e80-ae4e-11eb-8ec7-5bbf1418c734.png)

![image](https://user-images.githubusercontent.com/3970376/117316676-692a6400-ae4e-11eb-8994-7a648955a098.png)

<https://kovan.etherscan.io/tx/0x57a8e8371b4febd07a772877cb6c1e2d5b7bc939d63e307832881d9aa63de8fc> 

in user.balances.marketShares, user doesn't have a position or outcome shares. User does own the share tokens but UI isn't showing the user having that position

**Comment by Chwy5** [comment]
fixed
