### ISSUE TITLE
Market transaction table

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#427]
Transaction Table:

1) Move add/remove liquidity "Token Amount" value to "Share Amount" column. Delete "Token Amount" column

![Screen Shot 2021-05-06 at 10 01 15](https://user-images.githubusercontent.com/3970376/117320645-0dfa7080-ae52-11eb-9eda-2819a911d12b.png)

2) In header change "Swaps" to "Trades"

3) for Buy trades, change "Swap USDC for ..." to "Buy `outcome name`"

4) for Sell trandes, make first column say "Sell `outcome name`"

**Comment by Chwy5** [comment]
done - closing
