### ISSUE TITLE
Write test cases for liquidity provisioning to figure out how rounding errors are preventing adding liquidity

### ISSUE THREAD

**Issue by namankumar** [AugurProject/turbo#433]
rounding errors while adding liquidity is resulting in liquidity not being added. pls figure out and write out tests for liquidity provisioning with the most expansive coverage that at least includes:

1. use cases:
- add initial liquidity
- remove liquidity
- add liquidity + additional trading
- adding additional liquidity (second LP comes in)

2. variable values that at least cover known errors as well as some superset of the erroneous values.
- idea: maybe we can take the (approximate) distribution of each variable and run a simulation to generate result (shares, slippage, success/failure, etc). Then we can compare generated result vs. expected result to figure out which range of values is causing the errors. The test is well-written if it fails for the known erroneous values.

**Comment by justinbarry** [comment]
Did this for the most part. Took an array of usd amounts and add liquidity three times using all the combinations of said array.
