### ISSUE TITLE
show user's percentage of pool in LP Tokens in positions

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#443]
UI is going to be using percentages to display to the user the amount of liquidity
use pool TotalSupply to determine user's percentage of the pool

**Comment by bthaile** [comment]
closing this ticket. we are going in a different direction.

**Comment by bthaile** [comment]
repurposing this ticket for UI changes in liquidity portion of positions

**Comment by Chwy5** [comment]
added - closing
