### ISSUE TITLE
zero liquidity but prices are showing up in trading form

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#446]
when amm doesn't have liquidity show dashes for prices. 

![image](https://user-images.githubusercontent.com/3970376/117465733-9abb3200-af17-11eb-9b51-925d73c50456.png)

![Screen Shot 2021-05-07 at 09 38 05](https://user-images.githubusercontent.com/3970376/117466097-f71e5180-af17-11eb-9001-eed1c40b7072.png)

**Comment by Chwy5** [comment]
looks fixed - closing
