### ISSUE TITLE
LP percentage showing greater than 100%

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#471]
![Screen Shot 2021-05-11 at 09 35 12](https://user-images.githubusercontent.com/3970376/117833901-56dc6b80-b23c-11eb-8d08-93101cd7fd82.png)

**Comment by JohnDanz** [comment]
blocked by https://github.com/AugurProject/turbo/issues/477

**Comment by Chwy5** [comment]
fixed - closing
