### ISSUE TITLE
Style Cash out button

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#495]
To get shares in all outcomes, add liquidity then remove liquidity.

 ` Style "Cash out" button on portfolio page.
 ` Add "Cash out" button to single market page on position section. 

Messaging:
There are 3 scenarios
- can only cash out (show cash out message and Cash out button)
- can only claim winnings (show claim winnings message)
- can do both (show both messages and both buttons)

Portfolio page, same as single market but has the "Trade" button
![image](https://user-images.githubusercontent.com/3970376/118131811-9b930e80-b3c4-11eb-850b-1a78353f59da.png)

Mobile:
stack components
![image](https://user-images.githubusercontent.com/3970376/118131769-8ddd8900-b3c4-11eb-8b99-d3a7acb73312.png)

**Comment by JohnDanz** [comment]
This is now part of the `matic-dev` branch
