### ISSUE TITLE
PriceMarketFactory resolution can be manipulated

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/turbo#498]
`resolveMarket` in `PriceMarketFactory` determines the price to resolve to by calling this:

`uint256 _resolvedSpotPrice = pool.getSpotPriceSansFee(address(tokenIn), address(tokenOut));`

which will get the spot price of the relative token in a balancer pool at the time of calling.

This can be trivially manipulated to resolve in either direction and cash out on this by a contract that calls this function and performs the following steps:

1. Take out a flash loan for the collateral of the market
2. Mint "winning" tokens from the market via the `buy` method
3. Take out another flash loan for one of the tokens in the balancer pool
4. Use all the flash loaned balancer pool tokens to purchase the other token in the pool
5. Resolve the market. It will resolve in accordance with the manipulated spot price
6. Claim winnings on purchased market shares
7. Buy tokens to repay flash loans with winnings
8. Repay flash loans
9. Take profit

Step 2 could also source the winning shares by buying losing shares form anyone who holds them and if this is possible would be even more capital efficient since it wouldn't affect the pool size and would let someone in theory take _all_ the capital in the market fraudulently.

**Comment by robert-e-davidson3** [comment]
Since we only use(d) the PriceMarketFactory for testing, the solution here is to delete that contract.

However, would an averaged spot price over a period of time work? My understanding is that uniswap can do that.

**Comment by nuevoalex** [comment]
Yea a TWAP solution would prevent this

**Comment by robert-e-davidson3** [comment]
I renamed it to `TestPriceMarketFactory` and added a comment explaining that this cannot be used in production.
