### ISSUE TITLE
Solidity Refactor Investigation

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#57]
We aren't sure if this is a good idea or not, but answering these questions might be valuable:

1. Can we make TurboHatchery handle all collateral tokens?
2. If so, so we need a hatchery registry?
3. New turbos have a ton of information, much of which is encoded then passed along to its chosen arbiter without being captured by the hatchery. Should some of this information be stored in the hatchery? Should some more NOT be stored in the hatchery?
4. Should the hatchery provide mappings for easier turbo lookup or stick with just the array index of turbos?
5. Can we use create2 to simplify addressing?
6. Should turbo id really be an array index or should we use a hash we  can precalculate?

**Comment by justinbarry** [comment]
@robert-e-davidson3 Is this redundant of #80?

**Comment by justinbarry** [comment]
Closing, reopen if needed.
