### ISSUE TITLE
Connect to Polygon button silently fails in Brave browser

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#600]
I'm on ethereum mainnet and click the Connect to Polygon button. Nothing happens.

I expect it to visibly do something even if that something is showing an error modal.

In the console I see:
"The method 'wallet_addEthereumChain' does not exist / is not available."

**Comment by andrewdamelio** [comment]
@robert-e-davidson3 what version of Brave and which version of the MM extension are you using in brave?

**Comment by pgebheim** [comment]
Was marked as done
