### ISSUE TITLE
keep outcomes to one line market cards

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/turbo#614]
![image](https://user-images.githubusercontent.com/10524630/119408752-d857e300-bcab-11eb-8744-5119a1f01dae.png)

Portland Trailblazers should be one line not 2.

**Comment by pgebheim** [comment]
@andrewdamelio is this done?

**Comment by andrewdamelio** [comment]
still looking into this.

**Comment by andrewdamelio** [comment]
@JohnDanz is this still an issue? Did a bunch of testing this morning and they all look good -- was there a certain situation where this was happening like the image above? It looks like our breakpoints handle it well.

<img src="https://user-images.githubusercontent.com/1683736/121360068-14bd4d00-c902-11eb-8603-296a0cefce8c.png" width="200" />
