### ISSUE TITLE
Add LP warning "Liquidity should be removed before the final outcome is known."

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/turbo#626]

**Comment by Chwy5** [comment]
Impermanent loss occurs when you provide liquidity to a liquidity pool, and the price of your deposited assets changes compared to when you deposited them. The bigger this change is, the more exposed you are to impermanent loss. To mitigate this risk, it is recommended that you remove your liquidity before the final outcome is known.

**Comment by matt-bullock** [comment]
Add screen change: bold the text about removing liq. https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=2861%3A385

Confirmation screen change: Add message in green https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=2861%3A0

![image](https://user-images.githubusercontent.com/39496225/120489187-bbac6100-c3b7-11eb-945f-e8cfd41ff62b.png)
