### ISSUE TITLE
Hide spread markets that are identical to head-to-head markets

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#636]
Spread markets are shown even when the target spread is zero. Since this is identical to a head-to-head market, we should hide it to avoid liquidity fragmentation.

In an upcoming contract change, all lines will end in `5` so ties cannot happen. If the target home spread is exactly zero then it will be set to 0.5, which is `5` in the contract. So filter out spread markets whose "value" (target home spread) is exactly 5.

I want this filtering in the UI instead of on-contract because we use the existence or absence of a market as a signal to the link node for which markets to create. If we skip one then the link node will keep trying to create it.

**Comment by pgebheim** [comment]
Was this done, @andrewdamelio ?

**Comment by andrewdamelio** [comment]
@pgebheim  done!

**Comment by bthaile** [comment]
I think this should be done in contract-calls.ts not in the market view.

**Comment by pgebheim** [comment]
👍
