### ISSUE TITLE
Resolution procedure changes

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#656]
NOTE: These rules are not set in stone so work cannot proceed. Specifically, we don't know how we want to respond to timing changes.

- If an event is moved to a future date then its markets should resolve as No Contest. Have to check event time stability.
- Only resolve an event if its scores are stable.
- Resolve all events that should be resolved, not just those that finished in the past few days.

**Comment by robert-e-davidson3** [comment]
NOTE: This must include the resolution timestamp in a public method so the UI can get that information.

**Comment by robert-e-davidson3** [comment]
Depends on #818

**Comment by namankumar** [comment]
@robert-e-davidson3 what's the status of this, should we move it to another column or close it

**Comment by robert-e-davidson3** [comment]
@namankumar We've only done the third subtask so there's still work to do here.

**Comment by robert-e-davidson3** [comment]
The errors this is meant to avoid haven't manifested in practice so I'm closing this.
