### ISSUE TITLE
AMMFactory and MarketFactory belong together

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#658]
Their love can no longer be denied.

- In addresses.ts, put the AMMFactory under the MarketFactory so every market factory has one ammfactory.
- Deploy one AMMFactory for each market factory
- Make it so that AMMFactories only work with one MarketFactory.

These changes are needed for rewards and for a smoother upgrade procedure and for performance when there have been several upgrades.

**Comment by justinbarry** [comment]
This is a bigger architectural discussion that hopefully we can have in the future. For now the AMMFactory will keep a list of the blessed market factories (after rewards hits dev).
