### ISSUE TITLE
Ignore weights and just do 49 49 2

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#659]
The AMMFactory needs to just always set pool weights to 49 49 2 so weight trolling isn't possible.

Do not change the abi. Instead just ignore the weights parameter.

**Comment by pgebheim** [comment]
Should we remove this contract change from dev? It's not usable until the add liq code also swaps for the correct initial balances.

**Comment by robert-e-davidson3** [comment]
reevaluating
