### ISSUE TITLE
Wrong APY calculation

### ISSUE THREAD

**Issue by namankumar** [AugurProject/turbo#666]
APY displayed is wrong and throwing off potential LPs. Fix pls

![image](https://user-images.githubusercontent.com/330364/119925291-05b1c480-bf2a-11eb-8a90-b1717543a39b.png)

(red arrow is irrelevant)

![image](https://user-images.githubusercontent.com/330364/119924721-f7af7400-bf28-11eb-9c58-e331595c1d95.png)

**Comment by pgebheim** [comment]
This was double checked + added better formatting in #684
