### ISSUE TITLE
MMA O/U Total Rds

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/turbo#667]
Need to confirm contracts are working correctly and following these rules:

Bets referring to round/fight duration represents the actual time passed in the round/fight, as applicable, depending on the scheduled round/fight duration. For example a bet on Over 2.5 Total Rounds in a MMA fight will be settled as Over once a minute and a half in the 3rd Round has passed.

**Comment by robert-e-davidson3** [comment]
We dropped over-under for MMA.
