### ISSUE TITLE
Swap as part of creating pool

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#678]
We force new pool weights to be 2-49-49 so when the first LP adds liquidity, they add it at those prices. However, LPs will typically want to add liquidity add a different price based on their own expectation of where the market prices will be once trading starts.

Swapping to add liquidity is restricted to something like +50% of the swapped token in the pool. So the calculation required isn't as easy as "add min liquidity then swap for desired prices". The client will need to calculate the required initial liquidity to permit the single-token swaps needed to achieve the desired prices. Multiple swaps of a token are also possible but might not be desired... we need to figure that out.

- LPs will end up with a position they think is favorable based on how the prices they chose differ from the weights.
- This has to be in one transaction.
- The function's return must match addLiquidity aka it should return the lp tokens and the shares returned to the user (their position adjustment).
- This swapping is also useful for adding subsequent liquidity but suffers from the same +50% constraint.

**Comment by justinbarry** [comment]
Going to use the odds that come from the market as weights. New ticket #691
