### ISSUE TITLE
Use ethers.StaticJsonRpcProvider

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/turbo#680]
Search for StaticConnector and use that instead, it reduces RPC calls by not calling eth_chainId on every request.

**Comment by pgebheim** [comment]
@bthaile I'd like to schedule this for 1.1, it will reduce eth calls on initial market list loaf by removing the released calls to eth_chainId.

**Comment by pgebheim** [comment]
@andrewdamelio

**Comment by bthaile** [comment]
A long while ago, I used a static json rpc connector to reduce chattiness connecting to infura. 

I can't seem to find the actual connector in ethers or web3.

**Comment by pgebheim** [comment]
https://github.com/ethers-io/ethers.js/blob/ce8f1e4015c0f27bf178238770b1325136e3351a/packages/providers/src.ts/url-json-rpc-provider.ts#L28

StaticJsonRpcProvider

**Comment by bthaile** [comment]
ethers.providers.StaticJsonRpcProvider(infura_key);

found it as well.
