### ISSUE TITLE
do not create markets if rundown score.event_status_detail is TBD

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#693]
This is a change to the linknode adapter's market creation code to filter out events where `score.event_status_detail` is set to `TBD`.

Questions:
1. Will the value always be set to precisely `TBD` or are there variations in capitalization or characters used, like `Tbd` or `to be decided`?
2.  Are there other statuses aside from TBD we should be aware of?

**Comment by namankumar** [comment]
1. TBD seems to be it for now. I'll double check and post back
2. `event_status_detail` can supposedly take infinite number of values, it is not enumerated in any way! The other status should not affect our use case right now afaik. I've requested official docs and if I get them, I'll post'em

**Comment by namankumar** [comment]
@robert-e-davidson3 i'm sure you saw as well, posting for completeness - "It should be "TBD", but it's generally a good idea to .lower() or similar just to be safe."

**Comment by robert-e-davidson3** [comment]
Live on main!
