### ISSUE TITLE
Add NFL

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#726]
This is for contract changes plus any associated backend typescript changes.

See this [tech spec](https://github.com/AugurProject/turbo/blob/dev/specs/nfl-ncaa.md) for details.

The big changes:
- Support for NFL ties.
- Implement listResolvableEvents. The [robert/resolut](https://github.com/AugurProject/turbo/tree/robert/resolut) branch has this code with a similar name.

Work to be done:

- [x] #1037
- [x] #1038
- [x] #1039

**Comment by namankumar** [comment]
related to #819
