### ISSUE TITLE
Decide on reward payouts

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#742]
Three decisions need to made:
1. Amount of rewards per pool per block.
2. Bonus block period if we want to use one.
3. Should we be splitting the awards across pools and if so, how?

**Comment by pgebheim** [comment]
1. tbd
2. not to start
3. rewards should be split evenly across all markets in all pools. is this doable?

**Comment by justinbarry** [comment]
@pgebheim 3 is my preference as well. I'll try to get an idea of scope of work there.

**Comment by pgebheim** [comment]
Current rewards for current daily markets should (MLB, NBA) 95 MATIC / day, for 2 days.

**Comment by justinbarry** [comment]
ref #525
