### ISSUE TITLE
UI Implementation: changes for lp modifications based on figma

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/turbo#751]
@matt-bullock need design

The new banner shows even if user hasn't added liquidity, so it's always shown.

**Comment by namankumar** [comment]
dupe #808  @matt-bullock ?

**Comment by matt-bullock** [comment]
Link to desktop design: https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Augur-Simplified-UI?node-id=2973%3A0

Mobile design: https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Augur-Simplified-UI?node-id=2973%3A36659
