### ISSUE TITLE
Investigate re-architecture of market creation and management contracts

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#80]
Our current architecture is based on constraints that do not apply anymore. We no longer need a single connected system but can have specialized MarketFactory (name tbd) contracts for different kinds of markets. These can handle market creation (as from templates) and resolution.

We will have several fast resolution sources and many kinds of markets. The particulars of integrating them means much of the code will be one-offs. Trying to fit them all into one model is an exercise in overengineering.

Much of the code will be copy-pasted or shared as libraries. But that can happen organically as we add new MarketFactories and learn what generalizes and what doesn't.

**Comment by justinbarry** [comment]
Two assumption to add to the design.

1) Names of teams, symbols... human meanings of ID from the datasource are going to be in the UI
2) These monolithic template contracts will be whitelisted in the UI

**Comment by justinbarry** [comment]
We also need to discuss how to handle market creation from the oracle.... should this be as separate set of contracts, etc....
