### ISSUE TITLE
Fix open graph snippet

### ISSUE THREAD

**Issue by namankumar** [AugurProject/turbo#802]
When augur.net is shared across social media apps, the apps pull a snippet that is displayed in the preview. We want to modify this snippet to be more relevant to Turbo.

Current snippet:
![image](https://user-images.githubusercontent.com/330364/122468888-242b3e80-cf71-11eb-8de2-2623886e533d.png)

Changes to make:
1. add the REPv2 icon available https://augur.net/press-kit-and-logo-assets
2. change the wording to: 

> Augur is the world's most accessible, low-fee, no-limit betting platform. It allows you to buy and sell real-money stakes in world outcomes including sports, crypto, politics, and current events.

**Comment by namankumar** [comment]
@andrewdamelio This is looking great. Check out Twitter and FB messenger previews though. Is there a way to make those better? Suggestion: we could use the augur header image (attached below) for Twitter as it looks like the preview requires a larger image. 

Not sure what's up with FB. If high effort, we can even leave it as is since most of crypto doesn't live on FB.

Signal:
![image](https://user-images.githubusercontent.com/330364/134218870-b6aa6659-ae27-4b21-a646-b341c96c7b20.png)


Twitter:
![image](https://user-images.githubusercontent.com/330364/134218747-810a14f3-070b-4f61-baa4-e9c8adef129a.png)


iMessage:
![image](https://user-images.githubusercontent.com/330364/134218531-15840f22-a0b8-425d-a324-f8469e9de313.png)


Facebook messenger:
![image](https://user-images.githubusercontent.com/330364/134218495-cffd7f4b-62a2-4c26-be31-4ebf7980866c.png)




Augur header image:
![augurheader](https://user-images.githubusercontent.com/330364/134219499-756375fb-4361-4438-85d9-52405bd06c75.png)

**Comment by andrewdamelio** [comment]
@namankumar looking into this now
