### ISSUE TITLE
Create UI Design for LP Mods

### ISSUE THREAD

**Issue by namankumar** [AugurProject/turbo#808]
LP mods will be removed when liquidity is removed. Currently pending LP mods will be available to the UI. 

@matt-bullock follow up on signal / discord

**Comment by namankumar** [comment]
@matt-bullock does this ticket include the UI for bonus? Lmk and I can make a separate ticket for that if needed

**Comment by matt-bullock** [comment]
@namankumar There's a new ticket for that.

**Comment by namankumar** [comment]
@matt-bullock great, then closing this one
