### ISSUE TITLE
Develop chainlink node that packs data from the rundown

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#82]
For Market Creation
===

Event id needs to be hashed

For Resolution
===

This will need to lookup data from one of several sources. Will need to use the event_id to identify the data source.

**Comment by robert-e-davidson3** [comment]
Setting up the node is very involved but the instructions are extensive: https://docs.chain.link/docs/running-a-chainlink-node

However, the proposed node operator has already done that so all we need to provide them is the job specification: https://docs.chain.link/docs/job-specifications

The initiator would be `cron`: https://docs.chain.link/docs/initiators

We may need to write or find an adapter to pack everything into a single string that fits within bytes32: https://docs.chain.link/docs/developers#requesting-data
The rest of the tasks would be standard: http get, json parse, ethbytes32, ethtx.

**Comment by robert-e-davidson3** [comment]
I got a node running locally in docker, along with its database. The next step is to fund it, add a simple task, and see if it can interact with kovan.

**Comment by robert-e-davidson3** [comment]
The chainlink folks are on this.
