### ISSUE TITLE
UI needs Historic information

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#85]
UI needs
1. 24 hour trade volume per market (balancer pool)
2.market transaction history
 - outcome trade, (buy/sell)
   - We can copy the Balancer subgraph code
 - add/remove liquidity, 
   - Need to use our log for this to get USDC in and out of add/remove
 - claim winnings/fee history 
   - Comes from our log
 - balancer pool 24hr trade volume.
   - Comes for free with Balancer subgraph + time travel query

This information will come from the graph. This task is involves a few things:

- [ ] Setting up graph endpoints in the various deploy environments.
- [ ] Setup CI to deploy.
- [ ] Adding any relevant events to contracts

queries the UI will run to get info from sub graph, just a starting place. Le me know what is actually available
### Add Liquidity
    addLiquidity {
      id
      sender {
        id
      }
      tx_hash
      timestamp
      collateral
      lpTokens
    }
  }
☝️ if any shares are given to use as a result of adding liquidity, There shouldn't be but.

### Remove Liquidity

    removeLiquidity {
      id
      sender {
        id
      }
      tx_hash
      timestamp
      outcomes {
        id
        amount
      }
    }
  }
☝️ outcomes is the amount of shares the user received when removing liquidity

### buy
    buy {
      id
      sender {
        id
      }
      tx_hash
      timestamp
      outcomes {
        id
        amount
      }
      price
      cash
    }
  }
  ☝️ outcome is the outcome the user bought, cash is the amount of collateral they used to buy shares. price is the average price the user paid.
  
  ### sell
      sell {
      id
      sender {
        id
      }
      tx_hash
      price
      timestamp
      outcome {
         id
         amount
      }
      cash
    }
  }
  ☝️ outcome is the shares the user sold, cash is the amount of collateral they got back, price is the average price per shares they got. 
  
  ### claim winnings
      ClaimedProceeds {
      id
      sender {
        id
      }
      fees
      outcome
     marketId
     cash
      timestamp
      tx_hash
    }
☝️  cash is the amount of collateral they claimed, I think outcome is the outcome id winner, will need marketId of the maret the user claimed.

### claim fees
   ClaimedFees {
   id
   sender {
     id
    }
    cash
    marketId
    timestamp
    tx_hash
  }
  ☝️  claimed fees is new, need the user address, cash is collateral claimed.

**Comment by justinbarry** [comment]
This data will be needed from the graph.

**Comment by justinbarry** [comment]
This information will come from the graph. This task is involves a few things:

- [ ] Setting up graph endpoints in the various deploy environments.
- [ ] Setup CI to deploy.
- [ ] Adding any relevant events to contracts
