### ISSUE TITLE
different MLB games have same eventId

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#868]
Miami Marlins vs Philadelphia Phillies played two games but the event id is the same

Market factory: "0x4225c4fe9a02706c7bec927a3db25f29e273b3d1"
market indexes: "493", "375"

these events should have different eventIds
but both have "72d2afe8bee402f86a82215ad1dbfe69" on mumbai.

**Comment by namankumar** [comment]
Need to investigate to see if it's a one-off or repeated issue. Could be an adapter or data provider issue

**Comment by robert-e-davidson3** [comment]
IIRC this was due to running the canned markets script twice, and not having a contract-side block on creating an event twice. This has been resolved in the V3 contracts.
