### ISSUE TITLE
Keep crypto market factory from always redeploying

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#878]
Since the first resolution time is always different and is set in the constructor, deploying will always deploy the crypto market factory even if that's unnecessary.

**Comment by justinbarry** [comment]
The idea here is to move the resolution time bit out of the constructor and let the owner set it.

**Comment by robert-e-davidson3** [comment]
Did this as part of the demo setup because adding version for forcing redeploy caused a stack depth failure...
