### ISSUE TITLE
Give MLB its own MarketFactory without spread and OU

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#891]
This is just taking the SportsLinkMarketFactory.sol code and stripping it down.

We may also want to do some renaming since "SportsLink" is a bad name now.

**Comment by namankumar** [comment]
@robert-e-davidson3 is this a part of your refactor? Asking to understand current status of this ticket.

**Comment by robert-e-davidson3** [comment]
Yes it is.
